### PR TITLE
Set SNI hostname if we can for TLS connections

### PR DESCRIPTION
**Pull request by moparisthebest**
This patch sets the SNI hostname for TLS connections, using documented APIs for newer androids, and undocumented which works on most androids back to 2.3.  This is required for any TLS connection that requires SNI to pick the correct certificate to send to the client (or multiplex based on SNI, which is what I'm using it for).

### CODE REVIEW

**Comment by pocmo** [comment]
Thanks! This is looking good. I just have some nits.

**Comment by moparisthebest** [comment]
I've fixed your nits, and also realized I should add a minimum SDK check or the call could fail on older devices.

**Comment by pocmo** [comment]
Awesome! Thank you! :)

**Comment by pocmo** [comment]
Cherry-picked. c49c476cd04e80c0831c5c07f7f21a2ff886e20b

**Pull request closed without merging**
